spring:
  security:
    oauth2:
      client:
        provider:
          auth-server:
            issuer-uri: https://oauth2-auth-server-production.up.railway.app

        registration:
          auth-server:
            provider: auth-server
            client-id: auth-server
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "https://oauth2-gateway-production.up.railway.app/login/oauth2/code/auth-server"
            scope:
              - openid
              - profile
            client-authentication-method: client_secret_basic
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: resource-service
              uri: http://oauth2-resource-server.railway.internal:8080
              predicates:
                - Path=/api/**
              filters:
                - TokenRelay=

server:
  port: 8081